name: Publish update

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Enable experimental Docker features
        run: |
          mkdir -p ~/.docker
          echo "{\"experimental\": \"enabled\"}" > ~/.docker/config.json
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert GITHUB_REPOSITORY into lowercase
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Set tag environment variable
        run: |
          echo "TAG=ghcr.io/${REPO}" >>${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            FEATURES:expose-metrics
