name: Publish update
on: [push]

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Enable experimental Docker features
        run: |
          mkdir -p ~/.docker
          echo "{\"experimental\": \"enabled\"}" > ~/.docker/config.json
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert GITHUB_REPOSITORY into lowercase
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build for x86_64 with metrics
        run: |
          docker build --no-cache --build-arg FEATURES=expose-metrics -t http-proxy:metricsamd64 .
      - name: Create manifest and push it
        run: |
          docker tag http-proxy:metricsamd64 ghcr.io/${REPO}:metricsamd64
          docker push ghcr.io/${REPO}:metricsamd64
